### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by zhuanghemu** [staphopia/staphopia-sccmec#1]
/usr/bin/env: ‘python3’: Permission denied

**Comment by rpetit3** [comment]
Hi! Do you have have Python3 installed? 
```
which python3
```

**Comment by zhuanghemu** [comment]
> Hi! Do you have have Python3 installed?
> 
> ```
> which python3
> ```
I installed python 3.10(64-bit) in "C:\Users\78178\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.10"

**Comment by rpetit3** [comment]
Ah you're on Windows.

might want to try running it like `python3 staphopia-sccmec.py`

**Comment by zhuanghemu** [comment]
> python3 staphopia-sccmec.py

THANKS！ I run it successfully by using python staphopia-sccmec.py!

**Comment by rpetit3** [comment]
Hi @zhuanghemu 

Going to close this for now. Please feel free to re-open if the issue comes back!
