### ISSUE TITLE
Multiple SCCmec subtypes called

### ISSUE THREAD

**Issue by Kiratrea** [staphopia/staphopia-sccmec#11]
Hi I have a subset of isolates that were assigned two different subtypes (Ia/IIa). If this is a trustworthy result, is this indicating these samples have dual SCCmec types or could it mean some sort of hybridization? 

As always thanks so much for providing these tools!

**Comment by rpetit3** [comment]
Hi @Kiratrea 

Thank you for the kind words! Honestly, I doubt they have multiple SCCmec types. I think for these samples it would be worth looking into actual coverage against reference SCCmec Ia and IIa cassettes.

I've been meaning to revisit this tool and develop some way to easily add new cassettes, but here is a list of references:

https://github.com/staphopia/staphopia-sccmec/issues/4#issuecomment-1050524944

Let me know if I can help in anyway

**Comment by rpetit3** [comment]
Hi @Kiratrea 

It's been a while but I wanted to inform you that I have created a tool to replace this one.

Please check out https://github.com/rpetit3/sccmec to learn more! I will go ahead an close this as I am archiving this repo.

Cheers,
Robert
