### ISSUE TITLE
Will Continue updates/support? 

### ISSUE THREAD

**Issue by ajkarloss** [staphopia/staphopia-sccmec#12]
Hi, I am planning to use this tool for our research. I would like to know if yiou guys will continue to update and support?

**Comment by rpetit3** [comment]
Hi @ajkarloss,

Thank you for checking in. I plan to support it, but it is in need of some updates. I'm hoping to eventually move away from the in-silico PCR approach to some thing that is more robust and easiesr to add new cassettes.

Unfortunately, I do not have a timeline on when this might happen.

Cheers,
Robert

**Comment by ajkarloss** [comment]
Thanks a lot. I have sent you an email :)

**Comment by aharring83** [comment]
Hi Robert, how can a person assist you in updating the SCC mec types/subtypes? I made some minor attempts in the code to add new primers but currently facing problems with the predict_type_by_primers function and the primer_prediction = predict_type_by_primers(prefix, primer_hits, hamming_distance=args.hamming). I assume it might have do with setting hamming distances for the new primers? Any response will greatly appreciated, thank you.

**Comment by rpetit3** [comment]
Hi @aharring83 

I've been working on an updated tool.here https://github.com/rpetit3/sccmec

Check it out and let me know what you think!

**Comment by aharring83** [comment]
Will do, thank you so much. If you need any assistance, please don't hesitate to reach out.
Tony

**Comment by aharring83** [comment]
Robert, this is great, I love it! Thanks again

**Comment by rpetit3** [comment]
Thank you! If you think you can contribute in anyway I will not turn it down!

**Comment by rpetit3** [comment]
Hi all!

I will go ahead an close this as I am archiving this repo.

Please check out https://github.com/rpetit3/sccmec to learn more!

Cheers,
Robert
