### ISSUE TITLE
Non staph aueus species

### ISSUE THREAD

**Issue by smb20200615** [staphopia/staphopia-sccmec#2]
Hi,

Does staphopia-sccmec work for non staph aureus species (e.g staph epi?)

**Comment by rpetit3** [comment]
Hi @smb20200615 

I've never actually tried! I imagine if the primer scheme is the same then it should work.

I'd say give it a go and see what happens! If you do, would be very interested in the results.

Cheers, 
Robert

**Comment by smb20200615** [comment]
Thank you for your clarification. I am new to this area. Is there any computational way to tell if staph epi and staph aureus have the same primer scheme?

**Comment by rpetit3** [comment]
Hi @smb20200615 ,

I have created a tool to replace this one. which includes types I-XV. I will go ahead an close this as I am archiving this repo.

Please check out https://github.com/rpetit3/sccmec to learn more!

Cheers,
Robert
