### ISSUE TITLE
pbpC vs mecA

### ISSUE THREAD

**Issue by smb20200615** [staphopia/staphopia-sccmec#3]
Hello,

I am finding that the eggnog annotation for the mecA gene detected by the SCCfinder is the pbpC gene rather than the mecA gene. Are you searching for this protein https://www.ncbi.nlm.nih.gov/protein/1681032221? Apologies if this is a mistake on my side.

Best wishes,

**Comment by rpetit3** [comment]
Hi @smb20200615 

In this case I'm only searching for primers associated with mecA. 

I'm planning to revamp staphopia-sccmec here in the near future to hopefully make things a bit better.

Cheers!
Robert

**Comment by rpetit3** [comment]
Hi @smb20200615 

I have created a tool to replace this one. which includes types I-XV. I will go ahead an close this as I am archiving this repo.

Please check out https://github.com/rpetit3/sccmec to learn more!

Cheers,
Robert
