### ISSUE TITLE
Update to include latest SCCmec types

### ISSUE THREAD

**Issue by rpetit3** [staphopia/staphopia-sccmec#4]
https://www.mdpi.com/2079-6382/11/1/86

## SCCmec Types
![image](https://user-images.githubusercontent.com/5334269/153120048-9b6a84a2-b896-4c86-8452-7301fdfaa34f.png)

> 12. Katayama, Y.; Ito, T.; Hiramatsu, K. A new class of genetic element, staphylococcus cassette chromosome mec, encodes methicillin resistance in Staphylococcus aureus. Antimicrob. Agents Chemother. 2000, 44, 1549–1555. [CrossRef]

> 13. Ito, T.; Katayama, Y.; Asada, K.; Mori, N.; Tsutsumimoto, K.; Tiensasitorn, C.; Hiramatsu, K. Structural comparison of three
types of staphylococcal cassette chromosome mec integrated in the chromosome in methicillin-resistant Staphylococcus aureus. Antimicrob. Agents Chemother. 2001, 45, 1323–1336. [CrossRef]

> 19. García-Álvarez, L.; Holden, M.T.G.; Lindsay, H.; Webb, C.R.; Brown, D.F.J.; Curran, M.D.; Walpole, E.; Brooks, K.; Pickard, D.J.;
Teale, C.; et al. Meticillin-resistant Staphylococcus aureus with a novel mecA homologue in human and bovine populations in the UK and Denmark: A descriptive study. Lancet Infect. Dis. 2011, 11, 595–603. [CrossRef]

> 21. Ma, X.X.; Ito, T.; Tiensasitorn, C.; Jamklang, M.; Chongtrakool, P.; Boyle-Vavra, S.; Daum, R.S.; Hiramatsu, K. Novel type of
staphylococcal cassette chromosome mec identified in community-acquired methicillin-resistant Staphylococcus aureus strains.
Antimicrob. Agents Chemother. 2002, 46, 1147–1152. [CrossRef] [PubMed]

> 22. Ito, T.; Ma, X.X.; Takeuchi, F.; Okuma, K.; Yuzawa, H.; Hiramatsu, K. Novel type V staphylococcal cassette chromosome mec driven by a novel cassette chromosome recombinase, ccrC. Antimicrob. Agents Chemother. 2004, 48, 2637–2651. [CrossRef] [PubMed]

> 23. Oliveira, D.C.; Milheirico, C.; de Lencastre, H. Redefining a structural variant of staphylococcal cassette chromosome mec, SCCmec type VI. Antimicrob. Agents Chemother. 2006, 50, 3457–3459. [CrossRef] [PubMed]

> 24. Berglund, C.; Ito, T.; Ikeda, M.; Ma, X.X.; Soderquist, B.; Hiramatsu, K. Novel type of staphylococcal cassette chromosome mec in a methicillin-resistant Staphylococcus aureus strain isolated in Sweden. Antimicrob. Agents Chemother. 2008, 52, 3512–3516. [CrossRef]

> 25. Zhang, K.; McClure, J.A.; Elsayed, S.; Conly, J.M. Novel staphylococcal cassette chromosome mec type, tentatively designated type VIII, harboring class A mec and type 4 ccr gene complexes in a Canadian epidemic strain of methicillin-resistant Staphylococcus aureus. Antimicrob. Agents Chemother. 2009, 53, 531–540. [CrossRef] [PubMed]

> 26. Li, S.; Skov, R.L.; Han, X.; Larsen, A.R.; Larsen, J.; Sorum, M.; Wulf, M.; Voss, A.; Hiramatsu, K.; Ito, T. Novel types of
staphylococcal cassette chromosome mec elements identified in clonal complex 398 methicillin-resistant Staphylococcus aureus
strains. Antimicrob. Agents Chemother. 2011, 55, 3046–3050. [CrossRef]

> 27. Wu, Z.; Li, F.; Liu, D.; Xue, H.; Zhao, X. Novel type XII staphylococcal cassette chromosome mec harboring a new cassette
chromosome recombinase, CcrC2. Antimicrob. Agents Chemother. 2015, 59, 7597–7601. [CrossRef]

> 28. Baig, S.; Johannesen, T.B.; Overballe-Petersen, S.; Larsen, J.; Larsen, A.R.; Stegger, M. Novel SCCmec type XIII (9A) identified in an ST152 methicillin-resistant Staphylococcus aureus. Infect. Genet. Evol. 2018, 61, 74–76. [CrossRef] [PubMed]

> 29. Urushibara, N.; Aung, M.S.; Kawaguchiya, M.; Kobayashi, N. Novel staphylococcal cassette chromosome mec (SCCmec) type XIV (5A) and a truncated SCCmec element in SCC composite islands carrying speG in ST5 MRSA in Japan. J. Antimicrob. Chemother. 2020, 75, 46–50. [CrossRef]

## Subtypes
![image](https://user-images.githubusercontent.com/5334269/153120270-3e87a009-b9d8-491d-8929-a8de758dac9c.png)

> 12. Katayama, Y.; Ito, T.; Hiramatsu, K. A new class of genetic element, staphylococcus cassette chromosome mec, encodes methicillin resistance in Staphylococcus aureus. Antimicrob. Agents Chemother. 2000, 44, 1549–1555. [CrossRef]

> 13. Ito, T.; Katayama, Y.; Asada, K.; Mori, N.; Tsutsumimoto, K.; Tiensasitorn, C.; Hiramatsu, K. Structural comparison of three
types of staphylococcal cassette chromosome mec integrated in the chromosome in methicillin-resistant Staphylococcus aureus. Antimicrob. Agents Chemother. 2001, 45, 1323–1336. [CrossRef]

> 21. Ma, X.X.; Ito, T.; Tiensasitorn, C.; Jamklang, M.; Chongtrakool, P.; Boyle-Vavra, S.; Daum, R.S.; Hiramatsu, K. Novel type of
staphylococcal cassette chromosome mec identified in community-acquired methicillin-resistant Staphylococcus aureus strains.
Antimicrob. Agents Chemother. 2002, 46, 1147–1152. [CrossRef] [PubMed]

> 22. Ito, T.; Ma, X.X.; Takeuchi, F.; Okuma, K.; Yuzawa, H.; Hiramatsu, K. Novel type V staphylococcal cassette chromosome mec driven by a novel cassette chromosome recombinase, ccrC. Antimicrob. Agents Chemother. 2004, 48, 2637–2651. [CrossRef] [PubMed]

> 26. Li, S.; Skov, R.L.; Han, X.; Larsen, A.R.; Larsen, J.; Sorum, M.; Wulf, M.; Voss, A.; Hiramatsu, K.; Ito, T. Novel types of
staphylococcal cassette chromosome mec elements identified in clonal complex 398 methicillin-resistant Staphylococcus aureus
strains. Antimicrob. Agents Chemother. 2011, 55, 3046–3050. [CrossRef]

> 30. Shore, A.; Rossney, A.S.; Keane, C.T.; Enright, M.C.; Coleman, D.C. Seven novel variants of the staphylococcal chromosomal
cassette mec in methicillin-resistant Staphylococcus aureus isolates from Ireland. Antimicrob. Agents Chemother. 2005, 49, 2070–2083. [CrossRef]

> 31. Han, X.; Ito, T.; Takeuchi, F.; Ma, X.X.; Takasu, M.; Uehara, Y.; Oliveira, D.C.; de Lencastre, H.; Hiramatsu, K. Identification of a
novel variant of staphylococcal cassette chromosome mec, type II.5, and its truncated form by insertion of putative conjugative
transposon Tn6012. Antimicrob. Agents Chemother. 2009, 53, 2616–2619. [CrossRef]

> 32. Oliveira, D.C.; Milheirico, C.; Vinga, S.; de Lencastre, H. Assessment of allelic variation in the ccrAB locus in methicillin-resistant Staphylococcus aureus clones. J. Antimicrob. Chemother. 2006, 58, 23–30. [CrossRef]

> 33. Hisata, K.; Kuwahara-Arai, K.; Yamanoto, M.; Ito, T.; Nakatomi, Y.; Cui, L.; Baba, T.; Terasawa, M.; Sotozono, C.; Kinoshita, S.;
et al. Dissemination of methicillin-resistant Staphylococci among healthy Japanese children. J. Clin. Microbiol. 2005, 43, 3364–3372. [CrossRef]

> 34. Kondo, Y.; Ito, T.; Ma, X.X.; Watanabe, S.; Kreiswirth, B.N.; Etienne, J.; Hiramatsu, K. Combination of multiplex PCRs for
staphylococcal cassette chromosome mec type assignment: Rapid identification system for mec, ccr, and major differences in
junkyard regions. Antimicrob. Agents Chemother. 2007, 51, 264–274. [CrossRef] [PubMed]

> 35. Ma, X.X.; Ito, T.; Chongtrakool, P.; Hiramatsu, K. Predominance of clones carrying Panton-Valentine leukocidin genes among methicillin-resistant Staphylococcus aureus strains isolated in Japanese hospitals from 1979 to 1985. J. Clin. Microbiol. 2006, 44, 4515–4527. [CrossRef] [PubMed]

> 36. Kwon, N.H.; Park, K.T.; Moon, J.S.; Jung, W.K.; Kim, S.H.; Kim, J.M.; Hong, S.K.; Koo, H.C.; Joo, Y.S.; Park, Y.H. Staphylococcal
cassette chromosome mec (SCCmec) characterization and molecular analysis for methicillin-resistant Staphylococcus aureus and novel SCCmec subtype IVg isolated from bovine milk in Korea. J. Antimicrob. Chemother. 2005, 56, 624–632. [CrossRef] [PubMed]

> 37. Milheirico, C.; Oliveira, D.C.; de Lencastre, H. Multiplex PCR strategy for subtyping the staphylococcal cassette chromosome mec type IV in methicillin-resistant Staphylococcus aureus: ‘SCCmec IV multiplex’. J. Antimicrob. Chemother. 2007, 60, 42–48. [CrossRef]

> 38. Berglund, C.; Ito, T.; Ma, X.X.; Ikeda, M.; Watanabe, S.; Soderquist, B.; Hiramatsu, K. Genetic diversity of methicillin-resistant
Staphylococcus aureus carrying type IV SCCmec in Orebro County and the western region of Sweden. J. Antimicrob. Chemother.
2009, 63, 32–41. [CrossRef] [PubMed]

> 39. Iwao, Y.; Ishii, R.; Tomita, Y.; Shibuya, Y.; Takano, T.; Hung, W.C.; Higuchi, W.; Isobe, H.; Nishiyama, A.; Yano, M.; et al. The
emerging ST8 methicillin-resistant Staphylococcus aureus clone in the community in Japan: Associated infections, genetic diversity, and comparative genomics. J. Infect. Chemother. 2012, 18, 228–240. [CrossRef]

> 40. Hosoya, S.; Ito, T.; Misawa, S.; Yoshiike, T.; Oguri, T.; Hiramatsu, T. MRSA clones identified in outpatients dermatology clinic. J. Jpn. Assoc. Intectious Dis. 2014, 88, 840–848. (In Japanese)

> 41. Harris, T.M.; Bowen, A.C.; Holt, D.C.; Sarovich, D.S.; Stevens, K.; Currie, B.J.; Howden, B.P.; Carapetis, J.R.; Giffard, P.M.;
Tong, S.Y.C. Investigation of trimethoprim/sulfamethoxazole resistance in an emerging sequence type 5 methicillin-resistant
Staphylococcus aureus clone reveals discrepant resistance reporting. Clin. Microbiol. Infect. 2018, 24, 1027–1029. [CrossRef]

> 42. Hisata, K.; Ito, T.; Matsunaga, N.; Komatsu, M.; Jin, J.; Li, S.; Watanabe, S.; Shimizu, T.; Hiramatsu, K. Dissemination of multiple MRSA clones among community-associated methicillin-resistant Staphylococcus aureus infections from Japanese children with impetigo. J. Infect. Chemother. 2011, 17, 609–621. [CrossRef]

**Comment by rpetit3** [comment]
# SCCmec Types

| SCCmec Type | *Ccr*  Complex Type | *mec* Complex Type |  Link                                            | Notes                       |
|-------------|---------------------|--------------------|--------------------------------------------------|-----------------------------|
| Type Ia     | 1 (A1B1)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB033763.2/ |                             |
| Type Ib     | 1 (A1B1)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB433542    |                             |
| Type IIa    | 2 (A2B2)            | A                  | https://www.ncbi.nlm.nih.gov/nuccore/D86934      |                             |
| Type IIb    | 2 (A2B2)            | A                  | https://www.ncbi.nlm.nih.gov/nuccore/AB127982    |                             |
| Type IIc    | 2 (A2B2)            | A                  | https://www.ncbi.nlm.nih.gov/nuccore/AJ810120    |                             |
| Type IId    | 2 (A2B2)            | A                  | https://www.ncbi.nlm.nih.gov/nuccore/AB261975    |                             |
| Type IIe    | 2 (A2B2)            | A                  | https://www.ncbi.nlm.nih.gov/nuccore/AB127982    |                             |
| Type III    | 3 (A3B3)            | A                  | https://www.ncbi.nlm.nih.gov/nuccore/AB037671    |                             |
| Type IVa    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB063172    |                             |
| Type IVb    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB063173    |                             |
| Type IVc    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB096217    |                             |
| Type IVd    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB097677    |                             |
| Type IVg    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/DQ106887    |                             |
| Type IVh    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/HE681097    | integrated into chromosome? |
| Type IVi    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB425823    |                             |
| Type IVj    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB425824    |                             |
| Type IVk    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/GU122149    |                             |
| Type IVl    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB633329    |                             |
| Type IVm    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AB872254    |                             |
| Type IVn    | 2 (A2B2)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/KX385846    |                             |
| Type IVo    | 2 (A2B2)            | B                  | no sequence available?                           |                             |
| Type Va     | 5 (C1)              | C2                 | https://www.ncbi.nlm.nih.gov/nuccore/AB121219    |                             |
| Type Vb     | 5 (C1)              | C2                 | https://www.ncbi.nlm.nih.gov/nuccore/AB512767    | (5C2&5)                            |
| Type Vc     | 5 (C1)              | C2                 | https://www.ncbi.nlm.nih.gov/nuccore/AB505629    | (5C2&5)                           |
| Type VI     | 4 (A4B4)            | B                  | https://www.ncbi.nlm.nih.gov/nuccore/AF411935    |                             |
| Type VII    | 5 (C1)              | C1                 | https://www.ncbi.nlm.nih.gov/nuccore/AB373032    |                             |
| Type VIII   | 4 (A4B4)            | A                  | https://www.ncbi.nlm.nih.gov/nuccore/FJ390057    |                             |
| Type IX     | 1 (A1B1)            | C2                 | https://www.ncbi.nlm.nih.gov/nuccore/AB505628    |                             |
| Type X      | 7 (A1B6)            | C1                 | https://www.ncbi.nlm.nih.gov/nuccore/AB505630    |                             |
| Type XI     | 8 (A1B3)            | E                  | https://www.ncbi.nlm.nih.gov/nuccore/FR821779    | integrated into chromosome? |
| Type XII    | 9 (C2)              | C2                 | https://www.ncbi.nlm.nih.gov/nuccore/KR187111    |                             |
| Type XIII   | 9 (22)              | A                  | https://www.ncbi.nlm.nih.gov/nuccore/MG674089    |                             |
| Type XIV    | 5 (C1)              | A                  | https://www.ncbi.nlm.nih.gov/nuccore/LC440647    |                             |

**Comment by rpetit3** [comment]
# mec Classes

| *mec Classes  | Genes                                        | Source |
|----------------|-----------------------------------|---------|
| A                    | IS431-mecA-mecR1-mecI         | https://www.mdpi.com/2079-6382/11/1/86/htm |
| B                    | IS1272-ΔmecR1-mecA-IS431   | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC90469/ |
| C1                  | IS431-mecA-deltamecR1-IS431 | https://www.ncbi.nlm.nih.gov/pmc/articles/PMC90585/ |
| C2                  | IS431-mecA-deltamecR1-IS431 | https://www.mdpi.com/2079-6382/11/1/86/htm |
| E                     |  mecI–mecR1–mecA–blaZ  | https://www.sciencedirect.com/science/article/pii/S1473309911701268 | 

C1 & C2 is431 have different orientations

![image](https://user-images.githubusercontent.com/5334269/155661238-c52e519d-40e6-4abb-9978-96b23e50b84b.png)

**Comment by rpetit3** [comment]
For subtypes 
```
J regions: regions other than mec and ccr gene complexes.
Besides the mec and ccr gene complexes, the SCCmec element also contains three so-called J regions, 
which constitute nonessential components of the cassette. These regions may carry additional antimicrobial 
resistance determinants. They were first designated as the L-C, C-M, and I-R regions but were later changed 
to J regions. We propose that the term J region refers to “joining region,” rather than the previously 
used “junkyard region.”

J1 (formerly L-C) is the region between the right chromosomal junction and the ccr complex, J2 (C-M) is 
between the ccr gene complex and the mec gene complex, and J3 (I-R) is between the mec complex and 
the left chromosomal junction. Variations in the J regions within the same mec-ccr complex are used for 
defining SCCmec subtypes.
```

source https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2786320/

**Comment by incoherentian** [comment]
Hi Robert!  I think this would be the place you'd mention it if this tool's blastn db gets preliminary updates, so I'm posting here to be among the first to know as much as anything else :) 

P.S. FYI I ran a mini-workshop to get some graduate & project students up on bactopia for gram pos work last month - two of the participants were very excited about merlin giving them SCCmec results via this, yet another of your apparently infinite awesome tools :p IIRC one of the students had a potentially questionable negative result I didn't really consider again until seeing your ruminations in https://github.com/bactopia/bactopia/issues/467 referenced just above. I'm not too worried about that (probably from too low coverage honestly, training folks with their project isolates on old flow cells can be hit or miss), but it would be nice to have confidence that causation ≠ missing any types from the blastdb staphopia-sccmec.py points to. 

P.P.S. rumination revenge: With the incredible breadth amrfinder+ includes, I'm a little surprised it doesn't include all the SCCmec determinants. Perfect fit for the "+" expanded scope right? If it did you could probably skip the extra BLAST and "just" have a staphopia-sccmec script parse their %coverage and %ID from that preexisting output? A future amrfinder+ inclusion, hopefully, so db maintenance/hosting wouldn't fall to you :)

**Comment by rpetit3** [comment]
@incoherentian by chance are interested in testing https://github.com/rpetit3/sccmec ?

**Comment by JFsanchezherrero** [comment]
Looking forward for new updates and new sccmecs identified!

**Comment by rpetit3** [comment]
Hi all,

I have created a tool to replace this one. which includes types I-XV. I will go ahead an close this as I am archiving this repo.

Please check out https://github.com/rpetit3/sccmec to learn more!

Cheers,
Robert
