### ISSUE TITLE
How to retrieve the latest SCCmec types in the output

### ISSUE THREAD

**Issue by pany-vet** [staphopia/staphopia-sccmec#5]
Hi,

I noticed that the software outputs only contain the hits from SCCmec type I ~ type IVh. The same is shown in both the example test data and our genome sequences. I have checked the directory of the SCCmec reference data. The database also includes the SCCmec type VII, VIII, X, and XI. However, I can't find relevant results of the latest SCCmec types in the outputs.  I tried to use a genome carrying SCCmec-XI as an input file, but couldn't get the hit of XI in the result. 

I would like to know, how to make the software output the latest types?  And, how to update the SCCmec typing database (type XII or later)?

Thank you guys. @rpetit3

**Comment by rpetit3** [comment]
Hi @pany-vet 

I've started this issue https://github.com/staphopia/staphopia-sccmec/issues/4 where I plan on adding the newer SCCmec types. 

I unfortunately do not have a time line on this though, since it would have to be completed in my free time. I will try to revisit this soon to see if I'll be able to complete this sooner than later.

Thank you! 
Robert

**Comment by REMOUS-MAX** [comment]
Hi @rpetit3 

How are you doing, thanks for your usual effort to better this useful tool. Please did you manage to add the newer sccmec types?

**Comment by rpetit3** [comment]
@pany-vet and @REMOUS-MAX - Quite the coincidence! I have actually been thinking about this over the last week. 

One question I have is, do either of you have a list of S. aureus samples that have a lab validated SCCmec Type and raw genomic sequencing? I'm hoping to put together a test set to validate new changes

**Comment by REMOUS-MAX** [comment]
I have S. Aureus raw reads but the Sccmec have not been validated.
@rpetit3 do you need those with newer Sccmec types?

**Comment by rpetit3** [comment]
I think it would be useful to have a set of public samples with a known SCCmec type (e.g. pcr tested). Just to have a set to test against.

**Comment by REMOUS-MAX** [comment]
@rpetit3 I will ask around in my department to see if I can get some to share with you

**Comment by rpetit3** [comment]
Thank you so much!

**Comment by rpetit3** [comment]
Hi all!

I have created a tool to replace this one. which includes types I-XV. I will go ahead an close this as I am archiving this repo.

Please check out https://github.com/rpetit3/sccmec to learn more!

Cheers,
Robert
