### ISSUE TITLE
No mecA found (and no prediction) for MRSA strain

### ISSUE THREAD

**Issue by juanu** [staphopia/staphopia-sccmec#7]
Hi!

First of all, thanks for making this amazing tool available! I'm seeing a strange result, and wondering if this could be a problem on my end. 
I'm running the script against [this genome from NCBI](https://www.ncbi.nlm.nih.gov/assembly/GCA_000723965.1), and I'm getting `False` for all sccmec types and mecA.

When I check the annotation and run amrfinder on the same isolate, it can detect the mecA gene. I wonder if I'm making a mistake when running the script? I'm using this command:

```
staphopia-sccmec.py --assembly GCF_000723965.1_MV8_genomic.fna
```

And this is the output
```
sample	I	II	III	IV	V	VI	VII	VIII	IX	meca	Ia	IIa	IIb	IIIa	IVa	IVb	IVc	IVd	IVg	IVh
GCF_000723965.1_MV8_genomic	False	False	False	False	False	False	False	False	False	False	False	False	False	False	False	False	False	False	False	False
```

and the result showing the hamming distances

```
sample	I	II	III	IV	V	VI	VII	VIII	IX	meca	Ia	IIa	IIb	IIIa	IVa	IVb	IVc	IVd	IVg	IVh
cds_from_genomic	84	82	105	60	84	100	84	122	66	42	44	44	43	40	40	40	40	40	40	40
```

Any thoughts? Thank you!!!

**Comment by abourles** [comment]
Hi, I have the same problem, 
Any idea ? 
Thank you 
Alexandre

**Comment by rpetit3** [comment]
Hi @juanu !

I have created a tool to replace this one.  I will go ahead an close this as I am archiving this repo.

Please check out https://github.com/rpetit3/sccmec to learn more!

Cheers,
Robert
