### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by missingbeans** [staphopia/staphopia-sccmec#8]
(staphopia-sccmec) ubuntu:~/folder/contigs$ git clone git@github.com:staphopia/staphopia-sccmec.git
Cloning into 'staphopia-sccmec'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by rpetit3** [comment]
Hi @missingbeans 

In order to clone using `git` (instead of `https`) you will need to set up SSH keys. If you are just trying to make use of `staphopia-sccmec` you can install it through conda:

```
conda create -n staphopia-sccmec -c conda-forge -c bioconda staphopia-sccmec
```

**Comment by rpetit3** [comment]
Hi @missingbeans,

I have created a tool to replace this one.  I will go ahead an close this as I am archiving this repo.

Please check out https://github.com/rpetit3/sccmec to learn more!

Cheers,
Robert
