### ISSUE TITLE
Column annotations after "meca"

### ISSUE THREAD

**Issue by ShaokangZhang** [staphopia/staphopia-sccmec#9]
Thanks for providing this great tool! For the output, may I ask what tare the columns after "meca"? Are they the subtypes of SCCmec types? But if that's true, I found some of the SCCmec "subtypes" are different from SCCmec types. 

sample  I       II      III     IV      V       VI      VII     VIII    IX      meca    Ia      IIa     IIb     IIIa    IVa     IVb     IVc     IVd     IVg     IVh

Thanks so much!

**Comment by ShaokangZhang** [comment]
Will the SCCmec type X and XI be predicted?

**Comment by rpetit3** [comment]
Hi @ShaokangZhang 

I have created a tool to replace this one which includes types I-XV.  I will go ahead an close this as I am archiving this repo.

Please check out https://github.com/rpetit3/sccmec to learn more!

Cheers,
Robert
